site_name: 'Documentation Template'
repo_url: https://github.com/harness-idp-sandbox/care-super-shah-java
edit_uri: https://github.com/harness-idp-sandbox/care-super-shah-java/blob/main/docs/index.md

nav:
  - Home: index.md

plugins:
  - techdocs-core